// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDky-Q4bbQpmukZhaD5M_JxfoBJPs_14o0',
    appId: '1:749384103539:web:cb59a52d3a961ea51d5c06',
    messagingSenderId: '749384103539',
    projectId: 'health-bb01b',
    authDomain: 'health-bb01b.firebaseapp.com',
    storageBucket: 'health-bb01b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAXZUQD9gG_x5XQn-HtvJ8WtR0apJDJeM',
    appId: '1:749384103539:android:840af4ac09da55261d5c06',
    messagingSenderId: '749384103539',
    projectId: 'health-bb01b',
    storageBucket: 'health-bb01b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApBuD5WYJSybHds4ciLmJ3Ad5IRIbUReU',
    appId: '1:749384103539:ios:c1df04dd0417673a1d5c06',
    messagingSenderId: '749384103539',
    projectId: 'health-bb01b',
    storageBucket: 'health-bb01b.appspot.com',
    iosBundleId: 'com.example.health.ohealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApBuD5WYJSybHds4ciLmJ3Ad5IRIbUReU',
    appId: '1:749384103539:ios:dbc8adc81b4813bb1d5c06',
    messagingSenderId: '749384103539',
    projectId: 'health-bb01b',
    storageBucket: 'health-bb01b.appspot.com',
    iosBundleId: 'com.example.health.ohealth.RunnerTests',
  );
}
